iZettle/dropwizard-metrics-influxdb

.gitignore
pom.xml

- DropWizard v0.8.4 uses commons codec v1.9 so converge on that
Also:
- Adds enforcer execution to maven build
This was already there in the dropwizard-metrics upstream
[POM](https://github.com/dropwizard/metrics/blob/v3.1.1/pom.xml#L250-L267)
- Git ignore IDE stuff too

Downgrades commons-codec to v1.9

---

pom.xml
src/main/java/io/dropwizard/metrics/influxdb/InfluxDbReporter.java
src/test/java/io/dropwizard/metrics/influxdb/InfluxDbReporterTest.java

metrics v3 only requires java 1.6 so keep this artifact in sync

Back to Java v1.6 for metrics v3 compatibility

---

src/main/java/io/dropwizard/metrics/influxdb/InfluxDbReporter.java
src/test/java/io/dropwizard/metrics/influxdb/InfluxDbReporterTest.java

e.g. if we're only publishing every minute the timestamp will round down
to the nearest minute. This reduces InfluxDB storage requirements.
Closes #3

Rounds the reported timestamp down to the unit of time reported

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

This adds a set of default metrics excludes. The fields excluded are those redundant, static or uninteresting from a production perspective.

Adds default field excludes.

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

This makes the measurements more easily queryable in influxdb:
$ influx -database development -execute 'show measurements'
name: measurements
------------------
name
auth
client_connections
clients
connections
dao
datasources
health
http_server
jvm
jvm_buffers
jvm_classloader
jvm_gc
jvm_memory
jvm_threads
logs
raw_sql
resources
thread_pools

Map dots to underscores in jvm metrics

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/InfluxDbReporterFactoryTest.java
pom.xml

Set regular expression to map health metrics to the measurement `health`
when grouping guages. Since grouping gauges maps all health metrics to a
measurement like for example `com.example.health`.

Health gauges end in `health` when groupGauges is on

---

dropwizard-metrics-influxdb/pom.xml
dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/InfluxDbReporterFactoryTest.java
dropwizard-metrics-influxdb/src/test/resources/logback-test.xml
metrics-influxdb/pom.xml
metrics-influxdb/src/test/resources/logback-test.xml
pom.xml

- upticks version to v1.1.0 to signify the potential break of
compatibility
- uses the dropwizard-validation artifacts BaseValidator for testing
configuration deserialization, since that is what is used for
dropwizard configuration parsing.

Upgrades DropWizard dependencies to v0.9.1

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/InfluxDbReporterFactoryTest.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbHttpSender.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbReporterTest.java
metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java

Sometimes it takes InfluxDb longer to process a request than 1 second. This change increases the default to 1.5 seconds and allows for a configurable connect and read timeout to be set which will hopefully prevent the following type of data discard:
13:03:04,827 WARN  [com.izettle.metrics.influxdb.InfluxDbReporter] (metrics-influxDb-reporter-1-thread-1) Unable to report to InfluxDB. Discarding data.: java.net.SocketTimeoutException: connect timed out
at java.net.PlainSocketImpl.socketConnect(Native Method) [rt.jar:1.8.0_72]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) [rt.jar:1.8.0_72]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) [rt.jar:1.8.0_72]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl …

Adds configurable connect/read timeouts

---

findbugs/excludes.xml
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbHttpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbReporter.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbReporterTest.java
pom.xml

- Be quieter with exceptions
With our current use-case for metrics we don't particularly care too
much if a metric set has failed to report to influx. This library does
not retry after some time so it is still useful to have the message
but not necessarily the stack-trace.
- Adds findbugs analysis to the build

Adds findbugs and be quieter with exceptions

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbUdpSender.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbUdpSenderTest.java
metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java

Hi! There was a bug in InfluxDbUdpSender with time precision, partly described in #65 issue. Without setting time precision in nanoseconds it is unable to use InfluxDB in normal way. I've fixed it.

fixed bug with ignoring time precision by InfluxDbUdpSender

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbTcpSender.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbTcpSenderTest.java
metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java

We saw a fix for https://github.com/iZettle/dropwizard-metrics-influxdb/issues/65 applied for the UDP protocol.
It was fixed with https://github.com/iZettle/dropwizard-metrics-influxdb/pull/68
TCP has the same issue unfortunately, this pull request will modify the InfluxDB TCP sender to work as expect by the line protocol.

fixing time-unit issue in TCP Protocol. Line protocol uses nano seconds

---

README.md
dropwizard-metrics-influxdb/pom.xml
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
metrics-influxdb/pom.xml
pom.xml

By pushing new fields by default this change may have unintended
consequences which is why the minor version is ticked up.

Introduce new default percentile fields to push

---

README.md
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/SenderType.java
metrics-influxdb/pom.xml
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDBKafkaSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbLoggerSender.java

Added 2 implementations of InfluxDbBaseSender:
* InfluxDbLoggerSender - writes out influx db records to slf4j
* InfluxDBKafkaSender - writes out influx db records to kafka

Add senders

---

README.md
dropwizard-metrics-influxdb/pom.xml
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/TagTransformerType.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/tags/ClassBasedTransformer.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/tags/NoopTransformer.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/tags/PositionBasedTransformer.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/tags/Transformer.java
dropwizard-metrics-influxdb/src/main/resources/META-INF/services/com.izettle.metrics.dw.tags.Transformer
dropwizard-metrics-influxdb/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/tags/ClassBasedTransformer.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/tags/ClassBasedTransformerTest.java

This adds support in `dropwizard-metrics-influxdb` to configure a (tag) `Transformer`. And by default this is set to `ClassBasedTransformer`.
Closes #63
Conflicts with #75

Add tag transformer to dropwizard-metrics-influxdb

---

dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/InfluxDbReporterFactoryTest.java
dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/NoopTransformerTest.java
metrics-influxdb/pom.xml
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbBaseSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/tags/NoopTransformer.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbReporterTest.java
pom.xml

Ping @nzroller and @ngong, thanks.

Bump up dependencies.

---

metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbReporter.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbReporterTest.java

This is the same issue as reported in #78. For some reason, idle counters still get reported. It would be nice if we could not send anything from the client during its idle period.

Add support for skipping idle counters

---

metrics-influxdb/pom.xml
pom.xml

This seems to block many of our repos to build, including Sun.

Bump versions of Kafka and Dropwizard to avoid CVE errors

---

pom.xml

Bump Dropwizard to 1.3.17 to get version updates of included libraries.

Bump Dropwizard to 1.3.17

---

metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/GroupedInfluxDbHttpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbBaseSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbHttpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/GroupedInfluxDbHttpSenderTest.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializerTest.java

This is an attempt to get a change done by our company finally merged into the latest. See https://github.com/iZettle/dropwizard-metrics-influxdb/pull/72 for details on what this pull request is based on.
Here is the description from the original PR:
> Our organization needs to group all the fields under one measurement and transmit them as one measurement. This alternate serialization can be had by instantiating GroupedInfluxDbHttpSender instead of InfluxDbHttpSender.
There was a comment made by @rickard-von-essen-iz on 10/17/2017 requesting that a detailed documentation. This PR adds that detailed documentation and also merged in master from the main branch to bring it up to version 1.3.0 (it was based off version 1.1.9).
Please review and let me know if this needs further …

Allow grouping all measurements into one with multiple fields

---

README.md

- The default fields for timers has been p50, p75, p99, and p999 since
the 1.2.1 release, but the readme erroneously stated only the p50
and p99 were reported.

Update readme so that the fields documentation matches new defaults

---

metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbReporter.java

When collecting metrics having the same name as reserved influxdb keyword (time or tag), append an underscore to the field name to avoid the naming conflict.

Fix reserved influxdb field name when grouping gauges

---

README.md
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

https://github.com/dropwizard-jobs/dropwizard-jobs has built-in metrics that
could be registered in DW either manually or by using `JobsBundle`.
This PR adds mappings on such metrics and put them into measurement `jobs`.
It requires the job class to have `Job` at the end of its class name.

Add measurement mapping for jobs

---

.github/auto-merge.yml
.github/workflows/dependabot.yml

_Why?_ The main motivation is to ensure that this repo is continually up to date on the main branch. This ensures we are integrating dependency updates which include security patches as quickly as possible.
_How?_ This replaces some boilerplate Dependabot configuration with a [common Zettle approve and merge workflow](https://github.com/iZettle/.github/blob/main/.github/workflows/dependabot-approve-and-merge.yml)

Dependabot cleanup

---

.github/dependabot.yml

_Why?_ This repo produces public artifacts and shouldn't rely on private dependencies.
_Why?_ Hopefully gets dependabot to work again 
_Why?_ Hopefully closes #192 once dependabot kicks in

Dependabot: This public repo doesn't need private registry conf

---

.github/workflows/ecs-nightly-scans.yml

A PR request to enable nightly security scans of Zettle repos using Synpsys tools and ScanCLI **Please merge this PR ASAP**
Performing security scans on all code deployed to production is a vital part of any development workflow. It helps us 
prevent security issues from reaching production and reduces the cost of resolving such issues. Synopsys tools (BlackDuck 
and Coverity) were chosen by PayPal for use in all BUs when performing Static Application Security Testing (SAST) and 
Open-Source Security scanning (OSS). This PR implement the first step of the integration, nightly scans. Other, more 
involved integrations (e.g. PR scanning) will be implemented later on.
- This PR will add a new GitHub action to each repo. The action will run nightly. - No other changes are made to any files …

ECS - Implement Synopsys Nightly Scans
