src/main/java/io/dropwizard/metrics/influxdb/InfluxDbReporter.java
src/test/java/io/dropwizard/metrics/influxdb/InfluxDbReporterTest.java

Example:
"gauges" : {
"io.dropwizard.db.ManagedPooledDataSource.stats.active" : {
"value" : 0
},
"io.dropwizard.db.ManagedPooledDataSource.stats.idle" : {
"value" : 16
},
"io.dropwizard.db.ManagedPooledDataSource.stats.size" : {
"value" : 16
},
"io.dropwizard.db.ManagedPooledDataSource.stats.waiting" : {
"value" : 0
}
Given these gauges, if grouping is enabled the metric name will be
`io.dropwizard.db.ManagedPooledDataSource.stats` with fields `active`,
`idle`, `size` and `waiting`:
`io.dropwizard.db.ManagedPooledDataSource.stats`
| time                     | active | idle | size | waiting |
| 2015-10-06T13:56:30.751Z |      0 |   10 |   10 |       0 |
CAVEATS:
- This is a global option so not particularly convenient if your gauges
are not named like this
- If metric name terminates in a …

Adds optional gauge grouping to reporter

---

src/main/java/io/dropwizard/metrics/influxdb/InfluxDbReporter.java

- InfluxDb does not support field values of differing types
This means when we write `"value": "NaN"` we cannot write `"value":
1.0` later on. In addition `null` does not seem to be supported.
This change first converts double and float values that are NaN, -∞ or
∞ to null and then excludes null values completely from being
published.

Do not publish NaN and -∞ and ∞

---

src/main/java/io/dropwizard/metrics/influxdb/InfluxDbReporter.java
src/test/java/io/dropwizard/metrics/influxdb/InfluxDbReporterTest.java

Filters meter and timer fields.

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbHttpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbReporter.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbReporterTest.java
metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java

remove rounding, change precision to minute

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/InfluxDbReporterFactoryTest.java

Also:
- adds some more defaults
- adds a @ValidationMethod

Default measurement mappings correct regular expressions

---

README.md

- Adds build tool coordinates
- Adds typical required reporter configuration
- Adds a description of the default configuration
- Adds links to referenced projects

More detail in the readme

---

README.md
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

Default measurement mappings: add default for handlers and fix javadoc

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

Default measurement mappings: map event_handlers by messaging package

---

LICENSE

Closes #35
Ping @xiaodong-izettle and thanks @mnp

Adds Apache 2.0 License

---

findbugs/excludes.xml
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbBaseSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbHttpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbTcpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbUdpSender.java
metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java

Related #38 
Please review my code and tell me if there's something you want to change.

InfluxDbTcpSender + InfluxDbUdpListener

---

dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/SenderType.java
dropwizard-metrics-influxdb/src/test/java/com/izettle/metrics/dw/InfluxDbReporterFactoryTest.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbBaseSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbHttpSender.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbReporter.java
metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbTcpSender.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbHttpSenderTest.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbTcpSenderTest.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/InfluxDbUdpSenderTest.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/utils/TimeUtilsTest.java
metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java

Builder for new senders

---

metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java

Fix a bug on key and field escaping

---

metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializerTest.java

See https://github.com/iZettle/dropwizard-metrics-influxdb/issues/47

Ommit fields with values Double NaN's, +Inf, -Inf in line protocol

---

metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java
metrics-influxdb/src/test/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializerTest.java

See https://github.com/iZettle/dropwizard-metrics-influxdb/issues/45
and
https://docs.influxdata.com/influxdb/v0.13/write_protocols/line/#key

Fix tags and keys escaping

---

.travis.yml
dropwizard-metrics-influxdb/pom.xml
metrics-influxdb/pom.xml
pom.xml

refactored dependencies, use dropwizard 1.0

use dropwizard 1.0

---

README.md
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

This would fix the issue outlined in #59

Include `heap.usage` metric.

---

README.md
dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java

Reverts iZettle/dropwizard-metrics-influxdb#61

Revert "Include `heap.usage` metric."

---

dropwizard-metrics-influxdb/src/main/resources/META-INF/services/com.izettle.metrics.dw.tags.Transformer

Ping @rickard-von-essen-iz, thanks.

Use correct Transformer name.

---

dropwizard-metrics-influxdb/pom.xml
findbugs/excludes.xml
metrics-influxdb/pom.xml
pom.xml

Bump versions to support J11

---

dropwizard-metrics-influxdb/pom.xml
metrics-influxdb/pom.xml
pom.xml

Revert "Merge pull request #99 from iZettle/release130"
Revert "metrics-parent: prepare for next development iteration"
Revert "metrics-parent: prepare release v1.3.0"
Revert "Merge pull request #98 from iZettle/bump-kafka-and-dropwizard-to-avoid-cve-errors"

Revert of dep version bump + release

---

.travis.yml
metrics-influxdb/pom.xml
pom.xml

Bump up dependencies.

---

dropwizard-metrics-influxdb/pom.xml
metrics-influxdb/pom.xml
pom.xml

Release branch v1.3.1

---

dropwizard-metrics-influxdb/pom.xml
metrics-influxdb/pom.xml
pom.xml

- Allow grouping all measurements into one with multiple fields (#116) 
- Rename field named time to time_ when grouping gauges (#77)
- Add measurement mapping for jobs (#168)

Release 1.3.3

---

dropwizard-metrics-influxdb/pom.xml
metrics-influxdb/pom.xml
pom.xml

Changes
d096cf9 Bump basepom to 3.4.3
65da303 build(deps): bump mockito-core from 3.6.28 to 3.9.0
5804f0e build(deps): bump dropwizard.version from 2.0.15 to 2.0.21
ea5d03f build(deps): bump kafka-clients from 2.6.0 to 2.8.0
24b7c8f Add CODEOWNERS

Release 1.3.4
